### ISSUE TITLE
Hide the integration token

### ISSUE THREAD

**Issue by banhathome** [DevelopersGuild/zalgo-bot#1]
In zalgobot.js, line 6, you reveal the Slack integration token that the bot uses. This token is supposed to be a secret, otherwise anyone will be able to use it and possibly abuse it.

Also, Slack disabled the token because it was being abused I think, so Zalgobot no longer works.

**Comment by vihanchaudhry** [comment]
Yeah I just put it there because I didn't care and didn't expect anyone to want to abuse it. I don't think anyone did, but Slack saw it and disabled it. 
I went ahead and removed the old key, and I won't put the new one up. Hopefully Zalgo Bot will be back up soon! ^^

**Comment by pmer** [comment]
It's back up!
